#!/usr/bin/env node
/**
 * Remove build output.
 *
 *   npm run clean          .astro/ and dist/
 *   npm run clean -- --all  ...plus the generated public/ copies and the
 *                           Playwright report directories
 *
 * This exists because two gotchas ended in the same instruction. A stale
 * `.astro/` is what produces `[glob-loader] Duplicate id "<slug>"` after a
 * `docs.md` is created or replaced -- the content layer has the old entry
 * cached and re-syncs the new one under the same id. And a stale `dist/` makes
 * an edit to a source file look like a broken component, because `npm run
 * preview` is serving the previous build. Both are "remove the directory and
 * rebuild", which is a command, not a paragraph.
 *
 * Every path is a literal, and `public/` is named one subfolder at a time. It
 * is not a generated directory: `public/brand/` is hand-vendored from
 * theme-service and committed, and a glob here would delete it. `.gitignore`
 * names those four the same way, for the same reason.
 */
import { rm, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Astro's content-layer cache and its build output. */
const BUILD = ['.astro', 'dist'];

/** Written by sync-library.mjs, shots.mjs and Playwright. All regenerated by a run. */
const ALSO = [
  'public/library',
  'public/theme',
  'public/skill',
  'public/llms.txt',
  'shots',
  'test-results',
  'playwright-report',
  'blob-report',
];

const all = process.argv.slice(2).includes('--all');
const targets = all ? [...BUILD, ...ALSO] : BUILD;

const removed = [];
for (const target of targets) {
  const path = resolve(root, target);
  try {
    await stat(path);
  } catch {
    continue; // Already gone. Nothing to say about it.
  }
  await rm(path, { recursive: true, force: true });
  removed.push(target);
}

console.log(
  removed.length ? `clean: removed ${removed.join(', ')}` : 'clean: nothing to remove',
);
